### ISSUE TITLE
NXFilter under Nomad

### ISSUE THREAD

**Issue by mbravorus** [mockingbirdconsulting/HashicorpAtHome#6]
Hello,

I was wondering if you would be willingto share some configs pertaining to running NXFilter under Nomad (if you do run it under Nomad), or perhaps "outside" of Nomad control but on the same "server" node?

Thank you!

**Comment by proffalken** [comment]
Hey, I've dropped NXFilter from my network for the time being without finding a suitable replacement.

I had tried running it on a Raspberry Pi, however even though it's Java, there appears to be architecture dependent code within it that prevents it from running on armhf processors.

If it changes, I'll update/move the blog post and let you know, but I'm going to close this for now as it's not something I can help with, sorry :(
