### ISSUE TITLE
Blog Links mentioned in README.md for www.mockingbirdconsulting.co.uk/blog/ no longer work

### ISSUE THREAD

**Issue by lj020326** [mockingbirdconsulting/HashicorpAtHome#7]
Hi,

I love this repo and the blog article.  Together they are very helpful/educational and can easily be used demonstrate simple and advanced infrastructure setup concepts.

But now the DNS entry for www.mockingbirdconsulting.co.uk appears to no longer be found.

**Comment by proffalken** [comment]
Ah, yes, good spot, Mockingbird Consulting no longer exists as a company and the website is no longer online.

I've [recently written an updated version](https://www.budgetsmarthome.co.uk/tags/monitoring/)  and I'll update the README for this to point there instead.

Thanks!
